name: Push docs to GitHub Pages

on:
  push:
    branches: [ stable ]

jobs:
  push-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Build docs
        run: |
          pip install -r ./docs/requirements.txt
          python -m sphinx ./docs ./docs/_build

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          ref: gh-pages
          path: docs/gh-pages

      - name: Sync docs
        run: |
          rsync -a docs/_build/html/ docs/gh-pages/current/

      - name: Commit and push docs
        uses: magicstack/gha-commit-and-push@master
        with:
          target_branch: gh-pages
          workdir: docs/gh-pages
          commit_message: Automatic documentation update
          github_token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}
          ssh_key: ${{ secrets.RELEASE_BOT_SSH_KEY }}
          gpg_key: ${{ secrets.RELEASE_BOT_GPG_KEY }}
          gpg_key_id: "5C468778062D87BF!"