name: Deploy sphinx docs to GitHub Pages

on:
  push:
    branches: [stable]

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - id: deployment
        uses: sphinx-notes/pages@v3
